---
- name: Deploys the whole software stack for a CakePHP application
  hosts: development
  user: vagrant
  sudo: yes
  vars: 
    server_hostname: app.dev
    server_root: /vagrant/app/webroot

  roles:
    - system
    - php
    - nginx
    - percona
    - postgresql
    - redis
    - memcached
